Play travis
Otus-DevOps-2023-09/widoc84_infra pull request #1
Opened 2023-10-22 12:46 UTC by widoc84

Добаление ветки travis и исправление тестов

2023-10-23 08:30 UTC, mrgreyves requested changes
Здравствуйте!
ДЗ стоит выполнять в репозитории который был создан для вас
Перенесите свои наработки в него и выполняйте это дз в ветке play-travis
ДЗ возращаю на доработку

2023-10-23 10:37 UTC, widoc84 commented
В том репозитории у меня нет прав на коммиты

пн, 23 окт. 2023 г. в 11:30, Vladimir Drozdetskiy ***@***.***
>:

> ***@***.**** requested changes on this pull request.
>
> Здравствуйте!
> ДЗ стоит выполнять в репозитории который был создан для вас
> Перенесите свои наработки в него и выполняйте это дз в ветке play-travis
> ДЗ возращаю на доработку
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2023-09/widoc84_infra/pull/1#pullrequestreview-1691984385>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEVQ5DYXDX77Q34RRTS5DBDYAYTLFAVCNFSM6AAAAAA6K4DISWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMOJRHE4DIMZYGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-24 17:52 UTC, widoc84 commented
Пожалуйста вы либо дайте мне права на то чтобы я мог сам комитить, либо примите текущий pull request

2023-10-24 17:56 UTC, mrgreyves commented
Вы не приняли приглашение вовремя, по этому у вас не было прав
Добавил вам права, теперь можете смело пушить в ваш репозиторий =)

2023-10-24 20:24 UTC, widoc84 commented
Так и не получается создать ветку ни через gui ни запушить ее через git

PS F:\project\otus\widoc84_infra> git push --set-upstream origin play-travis
ERROR: Permission to Otus-DevOps-2023-09/widoc84_infra.git denied to widoc84.
fatal: Could not read from remote repository.      

Please make sure you have the correct access rights
and the repository exists.

2023-10-27 17:07 UTC, widoc84 commented
Можно дать права на создание бранчей и комиты?

2023-10-31 10:09 UTC, mrgreyves commented
![image](https://github.com/Otus-DevOps-2023-09/widoc84_infra/assets/34331259/ad2f6fbd-0158-4bec-93df-92b98233037f)
Приглашение все таки стоит принять, что бы доступ был

2023-10-31 10:10 UTC, mrgreyves commented
На всякий случай, приглашение я перевыслал еще раз, прямо сейчас

2024-02-24 09:33 UTC, closed without merging